/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.Login;

import Business.AdminPackage.Semester;
import Business.AdminPackage.BusinessLogic;
import Business.AdminPackage.FacultyDirectory;
import Business.AdminPackage.StudentDirectory;
import UserInterface.Login.Admin.AdminLoginJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import Business.CoursePackage.CourseCatalog;
import UserInterface.Login.Employer.EmployerLoginJPanel;
import UserInterface.Login.Student.StudentLoginJPanel;
import UserInterface.Login.Faculty.FacultyLoginJPanel;

/**
 *
 * @author dhwanil
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    StudentDirectory studentDir;
    FacultyDirectory facultyDir;
    CourseCatalog courseCatalog;
    BusinessLogic buslogic;
    
    
    public MainJFrame() {
        initComponents();
        //BusinessLogic default = new BusinessLogic();
        studentDir = new StudentDirectory();
        facultyDir = new FacultyDirectory();
        courseCatalog = new CourseCatalog();
        buslogic = new BusinessLogic(studentDir, facultyDir,courseCatalog);
        Semester.setSemester("f23");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplitPanel = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        AdminLoginBtn = new javax.swing.JButton();
        studentLogin = new javax.swing.JButton();
        professorLogin = new javax.swing.JButton();
        employerLogin = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainSplitPanel.setDividerLocation(150);

        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminLoginBtn.setText("Admin");
        AdminLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginBtnActionPerformed(evt);
            }
        });
        leftPanel.add(AdminLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 85, 85, -1));

        studentLogin.setText("Student");
        studentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLoginActionPerformed(evt);
            }
        });
        leftPanel.add(studentLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 139, 85, -1));

        professorLogin.setText("Professor");
        professorLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorLoginActionPerformed(evt);
            }
        });
        leftPanel.add(professorLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 194, -1, -1));

        employerLogin.setText("Employer");
        employerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employerLoginActionPerformed(evt);
            }
        });
        leftPanel.add(employerLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 251, -1, -1));

        mainSplitPanel.setLeftComponent(leftPanel);

        userProcessContainer.setBackground(new java.awt.Color(102, 102, 102));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        mainSplitPanel.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginBtnActionPerformed
        // TODO add your handling code here:
         AdminLoginJPanel adminLoginPage = new AdminLoginJPanel(userProcessContainer,buslogic.getStudentDirectory(),buslogic.getFacultyDirectory(),buslogic.getCourseCatalog());
         this.userProcessContainer.add("adminLoginPage",adminLoginPage);
         CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
         cardLayout.next(userProcessContainer);
     
    }//GEN-LAST:event_AdminLoginBtnActionPerformed

    private void professorLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorLoginActionPerformed
        // TODO add your handling code here:
        System.out.println(buslogic.getCourseCatalog());
        FacultyLoginJPanel facultyLoginPage = new FacultyLoginJPanel(userProcessContainer, buslogic.getStudentDirectory(),buslogic.getFacultyDirectory(),buslogic.getCourseCatalog());
        this.userProcessContainer.add("facultyLoginPage",facultyLoginPage);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);

        
    }//GEN-LAST:event_professorLoginActionPerformed

    private void studentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLoginActionPerformed
        // TODO add your handling code here:
        StudentLoginJPanel studentLoginPage = new StudentLoginJPanel(userProcessContainer, buslogic.getStudentDirectory(),buslogic.getFacultyDirectory(),buslogic.getCourseCatalog());
        userProcessContainer.add("studentLoginPage",studentLoginPage);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);

    }//GEN-LAST:event_studentLoginActionPerformed

    private void employerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employerLoginActionPerformed
        // TODO add your handling code here:
         EmployerLoginJPanel employerLoginJPanel = new EmployerLoginJPanel(userProcessContainer, buslogic.getStudentDirectory(),buslogic.getFacultyDirectory(),buslogic.getCourseCatalog());
         this.userProcessContainer.add("employerLoginJPanel",employerLoginJPanel);
         CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
         cardLayout.next(userProcessContainer);
        
    }//GEN-LAST:event_employerLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLoginBtn;
    private javax.swing.JButton employerLogin;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JSplitPane mainSplitPanel;
    private javax.swing.JButton professorLogin;
    private javax.swing.JButton studentLogin;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
