/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Login.Faculty;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.AdminPackage.FacultyDirectory;
import Business.AdminPackage.StudentDirectory;
import Business.CoursePackage.CourseCatalog;
import Business.AdminPackage.Faculty;

/**
 *
 * @author sai_vivek_vangala
 */
public class FacultyLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyLoginPage
     */
    JPanel userProcessContainer;
    StudentDirectory studentDir;
    FacultyDirectory facultyDir;
    CourseCatalog courseCatalog;

    public FacultyLoginJPanel(JPanel userProcessContainer, StudentDirectory studentDir, FacultyDirectory facultyDir, CourseCatalog courseCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.studentDir = studentDir;
        this.facultyDir = facultyDir;
        this.courseCatalog = courseCatalog;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bypassBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        facultyIdTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pwdTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bypassBtn.setText("Bypass");
        bypassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bypassBtnActionPerformed(evt);
            }
        });
        add(bypassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 6, -1, -1));

        jLabel2.setText("Faculty ID :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 225, 74, 22));

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 337, -1, -1));
        add(facultyIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 225, 197, -1));

        jLabel3.setText("password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 274, 74, 22));
        add(pwdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 274, 197, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("WELCOME TO FACULTY LOGIN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 139, 270, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String faculty_id = facultyIdTextField.getText();
        String pwd = pwdTextField.getText();
        if (faculty_id.isBlank() || pwd.isBlank())
            JOptionPane.showMessageDialog(this, "Admin id or password is emopty", "ERROR", JOptionPane.ERROR_MESSAGE);
        else {
            Faculty faculty = this.facultyDir.getFacultyByFacultyId(faculty_id);
            if (faculty != null) {
                if (faculty.getPassword().equals(pwd) && faculty.getIsAccActive()==true) {
                    System.out.println(courseCatalog);
                    FacultyLandingPageJPanel facultyLandingPage = new FacultyLandingPageJPanel(userProcessContainer, studentDir, faculty, courseCatalog);
                    this.userProcessContainer.add("facultyLandingPage", facultyLandingPage);
                    ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
                } else {
                    JOptionPane.showMessageDialog(this, "Faculty id or password incorrect", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void bypassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bypassBtnActionPerformed
        // TODO add your handling code here:
        Faculty faculty = this.facultyDir.getFacultyByFacultyId("ftest");
        FacultyLandingPageJPanel facultyLandingPage = new FacultyLandingPageJPanel(userProcessContainer, studentDir, faculty, courseCatalog);
        this.userProcessContainer.add("facultyLandingPage", facultyLandingPage);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);

    }//GEN-LAST:event_bypassBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bypassBtn;
    private javax.swing.JTextField facultyIdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField pwdTextField;
    // End of variables declaration//GEN-END:variables
}
