/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Login.Admin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.AdminPackage.FacultyDirectory;
import Business.AdminPackage.StudentDirectory;
import Business.CoursePackage.CourseCatalog;

/**
 *
 * @author dhwanil
 */
public class AdminMainWorksJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminMainOps
     */
    JPanel userProcessContainer;
    StudentDirectory studentDir;
    FacultyDirectory facultyDir;
    CourseCatalog courseCatalog;
    
    public AdminMainWorksJPanel(JPanel userProcessContainer, StudentDirectory studentDir, FacultyDirectory facultyDir, CourseCatalog coruseCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.studentDir = studentDir;
        this.facultyDir = facultyDir;
        this.courseCatalog = courseCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        manageFaculty = new javax.swing.JButton();
        manageStudent = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Admin Main Operations");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 168, -1));

        jLabel2.setText("Welcome Admin !");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 128, -1));

        manageFaculty.setText("Manage Faculty");
        manageFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFacultyActionPerformed(evt);
            }
        });
        add(manageFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 125, -1));

        manageStudent.setText("Manage Student");
        manageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStudentActionPerformed(evt);
            }
        });
        add(manageStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFacultyActionPerformed
        // TODO add your handling code here:
        ManageFacultyJPanel manageFaculty = new ManageFacultyJPanel(userProcessContainer, facultyDir);
        userProcessContainer.add("ManageFaculty", manageFaculty);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageFacultyActionPerformed

    private void manageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentActionPerformed
        // TODO add your handling code here:
        ManageStudentJPanel manageStudent = new ManageStudentJPanel(userProcessContainer, studentDir, courseCatalog);
        userProcessContainer.add(manageStudent);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageStudentActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.removeAll();

    }//GEN-LAST:event_homeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageFaculty;
    private javax.swing.JButton manageStudent;
    // End of variables declaration//GEN-END:variables
}
