/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Login.Admin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.AdminPackage.Student;
import Business.CoursePackage.Course;
import Business.CoursePackage.CourseCatalog;

/**
 *
 * @author dhwanil
 */
public class CourseInformationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GetStudentCourseInfoPanel
     */
    JPanel userProcessContainer;
    Student student;
    Course course;
    CourseCatalog courseCatalog;
    
    
    public CourseInformationJPanel(JPanel userProcessContainer, Student student,CourseCatalog coruseCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this .student = student;
        this.courseCatalog = courseCatalog;
        statusComboBox.removeAllItems();
        statusComboBox.addItem("Status");
        statusComboBox.addItem("PASS");
        statusComboBox.addItem("FAIL");
        populateTable();
    }
    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel)tblCourseDetails.getModel();
        dtm.setRowCount(0);
        for(Course course : student.getCourseList()){
            Object[] obj = new Object[2];
            obj[0] = course;
            obj[1] = course.getCourseName();
            dtm.addRow(obj);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseDetails = new javax.swing.JTable();
        viewMoreBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hideInOutPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        courseIdTextField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        gpaTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 242, -1, -1));

        tblCourseDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course ID", "Course Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourseDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 49, 592, 169));

        viewMoreBtn.setText("View");
        viewMoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMoreBtnActionPerformed(evt);
            }
        });
        add(viewMoreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 242, -1, -1));

        jLabel1.setText("Course Status");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 20, 157, -1));

        hideInOutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Course ID");
        hideInOutPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 59, 25));

        courseIdTextField.setEditable(false);
        courseIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseIdTextFieldActionPerformed(evt);
            }
        });
        hideInOutPanel.add(courseIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 7, 124, -1));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        hideInOutPanel.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 127, -1, -1));

        jLabel5.setText("Grade");
        hideInOutPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, 73, 25));

        gpaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaTextFieldActionPerformed(evt);
            }
        });
        hideInOutPanel.add(gpaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 44, 124, -1));

        jLabel6.setText("Course Status");
        hideInOutPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, -1, 25));

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        hideInOutPanel.add(statusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 75, -1, -1));

        add(hideInOutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 298, -1, -1));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String gpa = gpaTextField.getText();
        int index = statusComboBox.getSelectedIndex();
        if(index==-1 || gpa.isBlank() || this.course == null){
            JOptionPane.showMessageDialog(this, "Please Check Course or Course Status or gpa field", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String course_status = statusComboBox.getItemAt(index);
            this.student.getTranscript().setCourseStatus(String.valueOf(this.course.getCourseId()),course_status);
            this.student.getTranscript().setGrade(String.valueOf(this.course.getCourseId()), gpa);
            JOptionPane.showMessageDialog(this,"Information was Saved Successfully");
        }

        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void viewMoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMoreBtnActionPerformed
        // TODO add your handling code here:
        int index = tblCourseDetails.getSelectedRow();
        if(index==-1){
            JOptionPane.showMessageDialog(this, "Please select a row", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
            this.course = (Course)tblCourseDetails.getValueAt(index, 0);
            courseIdTextField.setText(String.valueOf(this.course.getCourseId()));            
            gpaTextField.setText(this.student.getTranscript().getGrade().get(String.valueOf(this.course.getCourseId())));
            
        }


    }//GEN-LAST:event_viewMoreBtnActionPerformed

    private void gpaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaTextFieldActionPerformed

    private void courseIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseIdTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField courseIdTextField;
    private javax.swing.JTextField gpaTextField;
    private javax.swing.JPanel hideInOutPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTable tblCourseDetails;
    private javax.swing.JButton viewMoreBtn;
    // End of variables declaration//GEN-END:variables
}
