/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Login.Admin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.AdminPackage.Faculty;
import Business.AdminPackage.FacultyDirectory;

/**
 *
 * @author dhwanil
 */
public class CreateFacultyCredentialsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateFacultyCredentials
     */
    JPanel userProcessContainer;
    FacultyDirectory facultyDir;

    public CreateFacultyCredentialsJPanel(JPanel userProcessContainer, FacultyDirectory facultyDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.facultyDir = facultyDir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fullNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        specialityTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        facultyIdTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pwdTextField = new javax.swing.JTextField();
        createUserBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Create Faculty Profile ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 75, -1, -1));

        jLabel2.setText("Full Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 133, 83, -1));
        add(fullNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 164, -1));

        jLabel3.setText("Speciality");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 168, 83, -1));
        add(specialityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 165, 164, -1));

        jLabel4.setText("Faculty ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 203, 83, -1));
        add(facultyIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 164, -1));

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 238, 83, -1));
        add(pwdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 235, 164, -1));

        createUserBtn.setText("Create Faculty Profile");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });
        add(createUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 304, -1, -1));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 558, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        // TODO add your handling code here:
        String full_name = fullNameTextField.getText();
        String speciality = specialityTextField.getText();
        String faculty_id = facultyIdTextField.getText();
        String pwd = pwdTextField.getText();
        int res = validateCredentials(full_name, speciality, faculty_id, pwd);
        boolean isExist = facultyDir.doesFacultyProfileExist(faculty_id);
        if (res == -1)
            JOptionPane.showMessageDialog(this, "No fields can be left empty", "ERROR", JOptionPane.ERROR_MESSAGE);
        else if (isExist) {
            JOptionPane.showMessageDialog(this, "Faculty ID already present", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            Faculty faculty = new Faculty();
            faculty.setFullName(full_name);
            faculty.setSpeciality(speciality);
            faculty.setFacultyId(faculty_id);
            faculty.setPassword(pwd);
            faculty.setIsAccActive(true);          
            facultyDir.addFacultyToFacultyDirectory(faculty);
            JOptionPane.showMessageDialog(this, "Information Saved Successfully");
            fullNameTextField.setText("");
            specialityTextField.setText("");
            facultyIdTextField.setText("");
            pwdTextField.setText("");
        }
    }//GEN-LAST:event_createUserBtnActionPerformed
    private int validateCredentials(String full_name, String speciality, String user_name, String pwd) {

        if (full_name.isBlank() || speciality.isBlank() || user_name.isBlank() || pwd.isBlank()) {
            return -1;
        } else {
            return 1;
        }
    }
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JTextField facultyIdTextField;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pwdTextField;
    private javax.swing.JTextField specialityTextField;
    // End of variables declaration//GEN-END:variables
}
