/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Login.Admin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.AdminPackage.Student;
import Business.AdminPackage.StudentDirectory;

/**
 *
 * @author dhwanil
 */
public class CreateStudentCredentialsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateUserCredentials
     */
    StudentDirectory studentDir;
    JPanel userProcessContainer;

    public CreateStudentCredentialsJPanel(JPanel userProcessContainer, StudentDirectory studentDir) {
        initComponents();
        this.studentDir = studentDir;
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fullNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        domainTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pwdTextField = new javax.swing.JTextField();
        createUserBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Create User Profile ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel2.setText("Full Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 83, -1));
        add(fullNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 164, -1));

        jLabel3.setText("Domain");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 83, -1));
        add(domainTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 164, -1));

        jLabel4.setText("Student ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 83, -1));
        add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 164, -1));

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 83, -1));
        add(pwdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 164, -1));

        createUserBtn.setText("Create Student Profile");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });
        add(createUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        // TODO add your handling code here:
        String full_name = fullNameTextField.getText();
        String domain = domainTextField.getText();
        String student_id = userNameTextField.getText();
        String pwd = pwdTextField.getText();
        int res = validateCredentials(full_name, domain, student_id, pwd);
        boolean isExist = studentDir.doesStudentProfileExist(student_id);
        if (res == -1)
            JOptionPane.showMessageDialog(this, "No fields can be left empty", "ERROR", JOptionPane.ERROR_MESSAGE);
        else if (isExist) {
            JOptionPane.showMessageDialog(this, "Student ID already present", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            Student student = new Student();
            student.setFullName(full_name);
            student.setDomain(domain);
            student.setUserId(student_id);
            student.setPassword(pwd);
            student.setIsAccActive(true);           
            studentDir.addStudentToStudentDirectory(student);
            JOptionPane.showMessageDialog(this, "Information Saved Successfully");
            fullNameTextField.setText("");
            domainTextField.setText("");
            userNameTextField.setText("");
            pwdTextField.setText("");
        }
    }//GEN-LAST:event_createUserBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);

    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JTextField domainTextField;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pwdTextField;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables

    private int validateCredentials(String full_name, String domain, String student_id, String pwd) {

        if (full_name.isBlank() || domain.isBlank() || student_id.isBlank() || pwd.isBlank()) {
            return -1;
        } else {
            return 1;
        }
    }
}
